version: "3.3"

services:
  db:
    container_name: njoy_product_registration
    image: mariadb:latest
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment: 
      MYSQL_DATABASE: registrationDB
      MYSQL_USER: NJOYUSERDB1
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my_db:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
    labels:
      name: "MySQL server"
volumes: 
  my_db: