
version: "3.3"

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatDB
    ports:
      - 5432:5432
    volumes:
      - pg_db:/var/lib/postgresql/data
    labels:
      name: "Postgres SQL Server"
volumes: 
  pg_db: